// Generated by CoffeeScript 1.9.3
(function() {
  var request;

  request = require('request');

  module.exports = {
    send: function(opt, cb) {
      var api;
      if (opt == null) {
        opt = {};
      }
      if (!cb) {
        cb = function(err, id) {
          if (err) {
            return console.log('SMS API:', err);
          }
        };
      }
      if (!opt.user || !opt.pass || !opt.sender || !opt.dest || !opt.msg) {
        return cb("Missing user/pass/sender/dest/msg");
      }
      api = opt.api || 'https://fast.smssolution.net.in/SendSMS/sendmsg.php';
      return request.post({
        url: api,
        form: {
          uname: opt.user,
          pass: opt.pass,
          send: opt.sender,
          dest: opt.dest,
          msg: opt.msg
        },
        rejectUnauthorized: false
      }, function(err, resp) {
        var regex;
        if (err) {
          return cb(err);
        }
        if ((regex = /0x\d+/.exec(resp.body))) {
          return cb("API Error code #" + regex[0]);
        }
        return cb(null, resp.body);
      });
    }
  };

}).call(this);
